export enum KafkaTopic {
    ACCESS_CACHE_INVALIDATION_DLQ = "access-cache-invalidation-dlq",
    ACCESS_CACHE_INVALIDATION     = "access-cache-invalidation",
    ACCESS_CACHE_SNAPSHOT_DLQ     = "access-cache-snapshot-dlq",
    ACCESS_CACHE_SNAPSHOT         = "access-cache-snapshot",
    PROJECTION_JOURNAL_DLQ        = "projection-journal-dlq",
    PROJECTION_JOURNAL            = "projection-journal",
    NOTIFICATION_DLQ              = "notification-dlq",
    IDENTIFIER_DLQ                = "identifier-dlq",
    NOTIFICATION                  = "notification",
    ACCOUNT_DLQ                   = "account-dlq",
    IDENTIFIER                    = "identifier",
    BLACKLIST                     = "blacklist",
    ACCOUNT                       = "account",
}
