export enum MessageTemplate {
    IDENTIFIER_VERIFICATION_OTP = "IDENTIFIER_VERIFICATION_OTP",
    ACCOUNT_VERIFICATION_OTP    = "ACCOUNT_VERIFICATION_OTP",
    RESET_PASSWORD_OTP          = "RESET_PASSWORD_OTP",
    LOGIN_OTP                   = "LOGIN_OTP"
}
